use_frameworks!

target 'SSCalendar_Example' do
  pod 'SSCalendar', :path => '../'

  target 'SSCalendar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
